import { FC } from "react";
import { List, ListItem, ListItemText } from "@mui/material";
import { map } from "lodash";
import { useNavigate } from "react-router-dom";

const CipherList: FC = () => {
	const navigate = useNavigate();
	const listOnClickHandler = (link: string) => navigate(link);

	return (
		<List>
			{map(messageExamples, ({ name, description, link }: MessageExample, index: number) => (
				<ListItem button key={index + link} onClick={() => listOnClickHandler(link)}>
					<ListItemText primary={name} secondary={description} />
				</ListItem>
			))}
		</List>
	)
}
interface MessageExample {
	name: string;
	description: string;
	link: string;
}

const messageExamples: readonly MessageExample[] = [
	{
		name: 'Reverse',
		description: "Makes a string of words in reverse",
		link: 'reverse',
	},
	{
		name: 'Birthday Gift',
		description: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
		link: 'test1',
	},
	{
		name: 'Recipe to try',
		description: 'I am try out this new BBQ recipe, I think this might be amazing',
		link: 'test2',
	},
	{
		name: 'Yes!',
		description: 'I have the tickets to the ReactConf for this year.',
		link: 'test3',
	},
	{
		name: "Doctor's Appointment",
		description: 'My appointment for the doctor was rescheduled for next Saturday.',
		link: 'test4',
	},
	{
		name: 'Discussion',
		description: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
		link: 'test5',
	},
	{
		name: 'Summer BBQ',
		description: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
		link: 'test6',
	},
];

export default CipherList;
